export const categories = [
  { value: "0", name: "All" },
  { value: "9", name: "General Knowledge" },
  { value: "10", name: "Books" },
  { value: "11", name: "Film" },
  { value: "12", name: "Music" },
  { value: "13", name: "Musicals & Theatres" },
  { value: "14", name: "Television" },
  { value: "15", name: "Vvalueeo Games" },
  { value: "16", name: "Board Games" },
  { value: "17", name: "Science & Nature" },
  { value: "18", name: "Computers" },
  { value: "19", name: "Mathematics" },
  { value: "20", name: "Mythology" },
  { value: "21", name: "Sports" },
  { value: "22", name: "Geography" },
  { value: "23", name: "History" },
  { value: "24", name: "Politics" },
  { value: "25", name: "Art" },
  { value: "26", name: "Celebrities" },
  { value: "27", name: "Animals" },
  { value: "28", name: "Vehicles" },
  { value: "29", name: "Comics" },
  { value: "30", name: "Gadgets" },
  { value: "31", name: "Japanese Anime & Manga" },
  { value: "32", name: "Cartoon & Animations" },
];
